### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by TimothyMarchant** [TimothyMarchant/PIC_Watch#1]
- [x] I2C Recovery methods (required; in case of a bus hang) //I've done all that I think I can do, I might control the I2C   //devices with IO pins at some point (supply power with the IO pin that is).
- [x] Use interrupts to update the screen when the time changes.
- [x] Implement more power saving functionality (use a pin to control the screen; that is stop giving power to the screen).
- [x] finalize Schematic
- [x] finish designing PCB
- [ ] Design the actual holder (the body of the actual watch) in CAD.
